//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category : DbEntity
    {
        public Category()
        {
            this.UserDetailsInCategories = new HashSet<UserDetailsInCategory>();
            this.UserInCategories = new HashSet<UserInCategory>();
            this.VacancyInCategories = new HashSet<VacancyInCategory>();
        }
    
        
        public string Name { get; set; }
    
        public virtual ICollection<UserDetailsInCategory> UserDetailsInCategories { get; set; }
        public virtual ICollection<UserInCategory> UserInCategories { get; set; }
        public virtual ICollection<VacancyInCategory> VacancyInCategories { get; set; }
    }
}
