//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Comment : DbEntity
    {
        public Comment()
        {
            this.VacancyInComments = new HashSet<VacancyInComment>();
        }
    
        public int UserId { get; set; }
        public int VacancyId { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<VacancyInComment> VacancyInComments { get; set; }
    }
}
