//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class CompanyDetail : DbEntity
    {
        public CompanyDetail()
        {
            this.Users = new HashSet<User>();
            this.Vacancies = new HashSet<Vacancy>();
        }
    
       
        public string Name { get; set; }
        public int TypeOfCompany { get; set; }
        public string WebSite { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Vacancy> Vacancies { get; set; }
    }
}
