//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public Education()
        {
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int Id { get; set; }
        public string Level { get; set; }
        public string Place { get; set; }
        public string Speciality { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
