//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobExperience
    {
        public JobExperience()
        {
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
        public string City { get; set; }
        public string Post { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
