//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int VacancyId { get; set; }
    
        public virtual SearchAgent SearchAgent { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
