//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchAgentsEmployer
    {
        public SearchAgentsEmployer()
        {
            this.SearchResultsEmployers = new HashSet<SearchResultsEmployer>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Request { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SearchResultsEmployer> SearchResultsEmployers { get; set; }
    }
}
