//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAtUa.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class UserDetail : DbEntity
    {
        public UserDetail()
        {
            this.UserDetailsInCategories = new HashSet<UserDetailsInCategory>();
            this.Users = new HashSet<User>();
        }
    
       
        public string Header { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> JobExperienceId { get; set; }
        public Nullable<int> EducationId { get; set; }
        public string Description { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual JobExperience JobExperience { get; set; }
        public virtual ICollection<UserDetailsInCategory> UserDetailsInCategories { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
